CREATE USER IF NOT EXISTS '${BLUEPRINT_DB_USERNAME}'@'%' IDENTIFIED BY '${BLUEPRINT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${BLUEPRINT_DB_DATABASE}.* TO '${BLUEPRINT_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
