CREATE DATABASE IF NOT EXISTS ${BLUEPRINT_DB_DATABASE};
CREATE USER IF NOT EXISTS '${BLUEPRINT_DB_USERNAME}'@'%' IDENTIFIED BY '${BLUEPRINT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${BLUEPRINT_DB_DATABASE}.* TO '${BLUEPRINT_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;


-- Create the users table if it doesn't exist
USE ${BLUEPRINT_DB_DATABASE};

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    saltedHashedPassword VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    sessionToken VARCHAR(255),
    csrfToken VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
