
services:
  app:
    image: ghcr.io/mstripling/hopp:latest
    restart: unless-stopped
    ports:
      - ${HOPP_PORT}:${HOPP_PORT}
    environment:
      HOPP_PORT: ${HOPP_PORT}
      HOPP_DB_HOST: mysql_hopp
      HOPP_DB_PORT: ${HOPP_DB_PORT}
      HOPP_DB_DATABASE: ${HOPP_DB_DATABASE}
      HOPP_DB_USERNAME: ${HOPP_DB_USERNAME}
      HOPP_DB_PASSWORD: ${HOPP_DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      mysql_hopp:
        condition: service_healthy
    networks:
      - hopp
  mysql_hopp:
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${HOPP_DB_DATABASE}
      MYSQL_USER: ${HOPP_DB_USERNAME}
      MYSQL_PASSWORD: ${HOPP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${HOPP_DB_ROOT_PASSWORD}
    ports:
      - "${HOPP_DB_PORT}:3306"
    volumes:
      - mysql_volume_hopp:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql_hopp", "-u", "${HOPP_DB_USERNAME}", "--password=${HOPP_DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - hopp

volumes:
  mysql_volume_hopp:
networks:
  hopp:

